INSERT INTO book (`book_id`, `title`, `content`, `image`, `description`, `create_at`, `update_at`) VALUES
    (1,
     'Harry Potter 1',
     '"Ông bà Dursley, nhà số 4 đường Privet Drive, tự hào mà nói họ hoàn toàn bình thường, cám ơn bà con quan tâm. Bà con đừng trông mong gì họ tin vào những chuyện kỳ lạ hay bí ẩn, đơn giản là vì họ chẳng hơi đâu bận tâm đến mấy trò vớ vẩn đó.\n"
                   "Ông Dursley là giám đốc một công ty gọi là Grunnings, chuyên sản suất máy khoan. Ông là một người cao lớn lực lưỡng, cổ gần như không có, nhưng lại có một bộ ria mép vĩ đại. Bà Dursley thì ốm nhom, tóc vàng, với một cái cổ dài gấp đôi bình thường, rất tiện cho bà nhóng qua hàng rào để dòm ngó nhà hàng xóm. Hai ông bà Dursley có một cậu quý tử tên là Dudley, mà theo ý họ thì không thể có đứa bé nào trên đời này ngoan hơn được nữa.\n"
                   "Gia đình Dursley có mọi thứ mà họ muốn, nhưng họ cũng có một bí mật, và nỗi sợ hãi lớn nhất của họ là cái bí mật đó bị ai đó bật mí. Họ sợ mình sẽ khó mà chịu đựng nổi nếu câu chuyện về gia đình Potter bị người ta khám phá. Bà Potter là em gái của bà Dursley, nhưng nhiều năm rồi họ chẳng hề gặp gỡ nhau. Bà Dursley lại còn giả đò như mình không có chị em nào hết, bởi vì cô em cùng ông chồng vô tích sự của cô ta chẳng thể nào có được phong cách của gia đình Dursley.\n"
                   "Ông bà Dursley vẫn rùng mình ớn lạnh mỗi khi nghĩ đến chuyện hàng xóm sẽ nói gì nếu thấy gia đình Potter xuất hiện trước cửa nhà mình. Họ biết gia đình Potter có một đứa con trai nhỏ, nhưng họ cũng chưa từng nhìn thấy nó. Đứa bé đó cũng là một lý do khiến họ tránh xa gia đình Potter: Họ không muốn cậu quý tử Dudley chung chạ với một thằng con nít nhà Potter.\n"
                   "Vào một buổi sáng thứ ba xám xịt âm u, ông bà Dursley thức dậy, chẳng hề cảm thấy chút gì rằng bầu trời đầy mây kia đang báo hiệu những điều lạ lùng bí ẩn sắp xảy ra trên cả nước Anh. Ông Dursley ậm ừ khi chọn cái cà-vạt chán nhất thế giới đeo vào cổ đi làm. Bà Dursley thì lách chách nói trong lúc vật lộn với cậu quý tử Dudley đang gào khóc vùng vẫy, không chịu ngồi ăn sáng tử tế. Không một ai để ý đến một con cú to và đen thui bay xẹt qua cửa sổ.\n"
                   "Tám giờ rưỡi, ông Dursley sách cặp, hửi cồ bà Dursley một cái và cố hôn cậu quý tử trước khi đi làm. Nhưng cậu Dudley đang chơi trò đánh trống thổi kèn, phun phèo phèo thức ăn và vun vãi mọi thứ tứ tung, kể cả cái hôn của cha. Ông Dursley vừa cười khoái chí: “Thằng chó con”, vừa đi ra khỏi nhà. Ông lên xe, lái ra khỏi ngôi nhà số 4 của mình.\n"
                   "Chính ở ngay góc đường, ông nhận thấy dấu hiệu đầu tiên của chuyện lạ: Một con mèo xem bản đồ. Thoạt tiên, ông Dursley không nhận ra đó là chuyện kỳ quái. Thế rồi ông giật mình quay lại nhìn lần nữa. Có một con mèo hoang đứng ở góc đường Privet Drive, nhưng bây giờ lại chẳng có tấm bản đồ nào cả! Chẳng lẽ chuyện đó là do ông tưởng tượng ra ư? Hay ánh sáng đã làm ông lóa mắt? Ông Dursley chớp chớp mắt rồi chăm chú nhìn con mèo. Nó cũng nhìn lại ông.\n"
                   "Ông lái xe vòng qua góc đường, đi tiếp, và tiếp tục nhìn con mèo qua kính chiếu hậu. Nó lúc ấy đang đọc bảng tên đường Privet Drive- À không, ngó bảng tên đường chứ, mèo đâu có thể đọc bảng tên đường hay xem bản đồ! Ông Dursley lắc lắc đầu, đuổi con mèo ra khỏi óc. Khi lái xe vào thành phố, ông không muốn nghĩ đến cái gì khác hơn là những đơn đắt hàng máy khoan mà ông mong có được nhiều thật nhiều trong ngày hôm đó.\n"
                   "Nhưng sắp vào tới thành phố, chợt có một việc khiến ông không còn tâm trí nghĩ đến những chiếc máy khoan nữa: lúc ngồi đợi trong xe, giữa dòng xe cộ kẹt cứng, ông không thể không nhận thấy hình như xung quanh có rất nhiều người ăn mặc lạ lùng đang lảng vảng. Tất cả bọn họ đều mặc áo trùm kín. Ông Dursley vốn đã không chịu nổi bọn người ăn mặc dị hợm- những thứ lôi thôi mà đám trẻ vẫn mặc!- nên ông cho là lần này chắc lại là một thời trang ngu ngốc nào đó xuất hiện.\n"
                   "Ông sốt ruột nhịp ngón tay trên tay lái xe hơi và ánh mắt ông đụng nhằm một cặp quái đang chụm đầu đứng gần đó. Họ đang thì thầm với nhau coi bộ rất kích động. Ong Dursley giận sôi lên khi nhận thấy cặp này cũng chẳng còn trẻ gì: Coi, gã đàn ông trông còn già hơn cả ông, vậy mà lại khoác áo trùm màu xanh ngọc bích! Chẳng ra thể thống gì cả! Đầu óc gì thế chứ! Nhưng ông Dursley chợt giật mình- hình như những người này đang tụ tập vì một chuyện gì đó… Ừ, hình như vậy!…\n"
                   "Dòng xe cộ thông, và chỉ vài phút sau ông Dursley đã lái xe vào bãi đậu của hãng Grunnings, đầu óc ông giờ đã quay trở lại với mấy cái máy khoan.\n"
                   "Trong văn phòng ở lầu chín, ông Dursley thường vẫn hay ngồi quay lưng lại cửa sổ. Giả sử không ngồi kiểu đó, thì rất có thể sáng hôm ấy ông sẽ khó tập trung được vô mấy cái máy khoan. Bởi ngồi như vậy, nên ông đã không thấy, bên ngoài cửa sổ, một đàn cú bay lượn xao xác giữa ban ngày. Mọi người dưới phố đều trông thấy, nhưng ông Dursley thì không. Người ta chỉ trỏ kinh ngạc, thậm chí há hốc mồm khi ngước nhìn đàn cú bay vụt qua ngay trên đầu, nhiều người trong số đám đông ấy thậm chí chưa từng thấy một con cú vào nửa đêm, đừng nói chi giữa ban ngày như thế này.\n"
                   "Ai cũng thấy chỉ riêng ông Dursley là không thấy. Ông đã trãi qua một buổi sáng hoàn toàn bình thường, không có cú. Sáng đó, ông quát tháo năm người khác nhau. Ông gọi nhiều cú điện thoại quan trọng và la hét thêm một hồi. Tâm trạng ông sảng khoái cho đến bữa ăn trưa, và tự nhủ mình phải duỗi chân cẳng một chút, băng qua đường, mau cho mình một cái bánh ở tiệm bánh mì.\n"
                   "Ông hầu như đã quên bén những người khoác áo trùm kín cho tới khi đi ngang qua một đám người đứng gần tiệm bánh. Cả bọn đều mặc áo trùm. Ông nhìn họ giận dữ. Ông không biết tại sao, nhưng họ làm ông khó chịu quá. Bọn này thì thào với nhau có vẻ rất kích động, mà ông thì không nghe được tí teọ nào. Chỉ đến lúc trên đường về từ tiệm bánh mì, đi ngang qua đám người khoác áo trùm, ông Dursley mới nghe lõm bỏm được những gì họ nói:\n"
                   "- Gia đình Potter, đúng đấy. Tôi nghe đúng như thế…\n"
                   "- … Ừ, con trai họ, Harry…\n"
                   "Ông Dursley đứng sững lại, chết lặng. Ông ngợp trong nỗi sợ hãi. Ông ngoái nhìn đám người đang thì thào như muốn nói gì với họ, nhưng rồi lại thôi.\n"
                   "Ông băng nhanh qua đường, vội vã về văn phòng, nạt viên thư ký là đừng có quấy rầy ông, rồi cầm điện thoại lên, sắp quay xong số gọi về nhà thì lại đổi ý. Ông đặt ống nghe xuống, tay rứt rứt hàng ria, suy nghĩ… Không, ông hơi hồ đồ. Potter đâu phải là một cái họ hiếm hoi gì. Ông dám chắc là có hàng đống người mang họ Potter và đặt tên con mình là Harry. Nghĩ đi nghĩ lại thật kỹ, ông thấy cũng không chắc thằng cháu của ông tên là Harry. Ông chưa từng gặp nó. Biết đâu nó tên là Harvey hay Harold. Chẳng việc gì ông phải làm phiền đến bà Dursley; bả luôn luôn nổi giận và buồn bực khi nghe nhắc đến cô em gái của mình. Ông cũng chẳng trách bà, ông cũng sẽ thế thôi nếu ông có một cô em gái như thế… Nhưng mà em của bà hay em của ông thì đằng nào cũng vậy. Nhưng… cái bọn khoác áo trùm!…\n"
                   "Buổi trưa đó, ông bỗng thấy khó mà tập trung vô mấy cái máy khoan, và khi rời sở làm lúc năm giờ chiều thì ông trở nên lo âu và căng thẳng đến nỗi đâm sầm vào một người ở ngoài cửa.\n"
                   "- Xin lỗi!\n"
                   "Ông càu nhàu với người đàn ông nhỏ thó bị ông đâm vào làm cho suýt ngã bổ ra sau. Nhưng chỉ vài giây sau, ông Dursley chợt nhận ra là gã đàn ông đó cũng khoác áo trùm màu tím. Gã không tỏ vẻ cáu giận về chuyện gã suýt bị lăn quay ra đất. Ngược lại, mặt gã giãn ra một nụ cười toe toét, và gã nói với một giọng mơ hồ khiến mọi người đi ngang phải ngoái nhìn.\n"
                   "- Đừng lo, thưa ngài, hôm nay không có gì có thể làm tôi nổi cáu được đâu. Vui lên đi. Bởi vì kẻ – mà – ai – cũng – biết – là – ai – đấy cuối cùng đã biến rồi! Ngay cả dân Muggle như ngài cũng nên ăn mừng cái ngày vui vẻ, rất vui vẻ này đi.\n"
                   "Và gã đàn ông ôm ngang người ông Dursley một cách thân tình rồi bỏ đi.\n"
                   "Ông Dursley đứng như trời trồng tại chỗ. Ông bị một người hoàn toàn xa lạ ôm thân tình một cái! Ông lại bị gọi là dân Muggle, không biết là cái quỷ gì? Ông ngạc nhiên quá. Vội vã ra xe, ông lái về nhà, hy vọng là những gì xảy ra chẳng qua là do ông tưởng tượng mà thôi. Nhưng mà trước nay, cókhi nào ông công nhận là có trí tưởng tượng ở trên đời đâu!\n"
                   "Khi cho xe vào ngõ nhà số 4, cái trước tiên mà ông nhìn thấy – và cũng chẳng làm cho ông dễ thở hơn chút nào – là con mèo hoang to tướng mà ông đã thấy hồi sáng. Con mèo đang ngồi chong ngóc trên bờ tường khu vườn nhà ông. Ông chắc là đúng con mèo hồi sáng, bởi quanh mắt nó cũng có viền hình vuôn. Ông Dursley xuỵt lớn:\n"
                   "- Xù.\n"
                   "Con mèo chẳng thèm nhúc nhíc. Nó còn nhìn lại ông một cách lạnh lùng. Ông Dursley thắc mắc. Không biết có phải kiểu cư xử thông thường của mèo là vậy? Cố gắng lấy lại vẻ tự chủ, ông đĩnh đạc bước vào nhà. Ông vẫn còn quyết tâm là sẽ không nói gì với vợ về chuyện Potter.\n"
                   "Bà Dursley cũng trãi qua một ngày bình thường tốt đẹp. Trong bữa ăn tối, bà kể cho chồng nghe chuyện rắc rối của nhà hàng xóm và con gái của họ, cùng chuyện hôm nay Dudley học nói được thêm hai từ mới (“hổng thèm”). Ông Dursley cố gắng cư xử như bình thường. Khi bé Dudley được đặt lên giường ngủ thì ông vào phòng khách để xem bản tin buổi tối.\n"
                   "- Và cuối cùng, thưa quý vị khán giả, những người quan sát cầm điểu khắp nơi báo cáo là chim cú trên cả nước đã hành động hết sức bất thường suốt ngày hôm nay. Mặc dù cú thường đi săn vào ban đêm và ít khi xuất hiện vào ban ngày, nhưng cả ngày nay, từ sáng sớm, đã có hàng trăm con cú bay tứ tán khắp mọi hướng. Các chuyên viên không thể giải thích nổi tại sao cú lại thay đổi thói quen thức ngủ như vậy.\n"
                   "Phát ngôn viên nói tới đây tự thưởng cho mình một nụ cười rồi tiếp:\n"
                   "- Cực kỳ bí hiểm. Và bây giờ là phần dự báo thời tiết của Jim McGuffin. Liệu đêm nay còn trận mưa cú nào nữa không Jim?\n"
                   "Người dự báo thời tiết đáp:\n"
                   "- À, tôi không rành vụ đó lắm,nhưng ngày hôm nay không chỉ có cú hành động quái chiêu, mà thời tiết cũng tỏ ra bất bình thường. Nhiều quan sát viên ở các vùng khác nhau đã gọi điện thoại phàn nàn với tôi là thay vì một trận mưa như tôi đã dự báo ngày hôm qua, thì họ lại nhận được một trận sao băng. Không chừng người ta ăn mừng lễ đốt pháo bông quá sớm, nhưng thưa bà con, tuần sau mới tới ngày đốt pháo bông mà! Dù vậy tôi xin cam đoan là thời tiết tối nay sẽ rất ẩm ướt.\n"
                   "Ông Dursley ngồi như đóng băng trên ghế bành. Sao băng trên khắp bầu trời Anh – cát – lợi à? Cú bay lượn vào ban ngày ư? Những con người khoác áo trùm bí ẩn khắp nơi nữa chứ. Và… và những câu chuyện thì thào về gia đình Potter…\n"
                   "Bà Dursley bưng hai tách trà vào phòng. Không ổn rồi. Ông phải nói gì với bà thôi. Ông tằng hắng lấy giọng:\n"
                   "- Ờ… em à… lâu nay em không nghe nói gì về em gái của em phải không?\n"
                   "- Không.\n"
                   "Đúng như ông “mong đợi”, bà Dursley giật mình và đổ quạu. Chẳng phải là lâu nay cả hai đã ngầm coi như bà chẳng hề có chị em gì hết sao? Giọng bà sắc lẻm:\n"
                   "- Mà sao?\n"
                   "Ông Dursley lầu bầu:\n"
                   "- À, chỉ là ba mớ tin tức… cười. Nào là cú… sao băng… lại có cả đống bọn khoác áo trùm nhôn nhạo dưới phố hôm nay…\n"
                   "- Thì sao? – Bà Dursley ngắt ngang.\n"
                   "Ông Dursley vội phân bua:\n"
                   "- Ờ… anh chỉ nghĩ… có thể… có chuyện gì đó dính dáng tới dì nó… em biết đó… dì nó…\n"
                   "Bà Dursley nhấp môi son vào tách trà. Ông Dursley băn khoăn không biết liệu mình có dám nói với vợ là đã nghe thiên hạ bàn tán về cái tên “Potter” không.Cuối cùng ông không dám. Thay vào đó, ông cố làm ra vẻ hết sức bình thường:\n"
                   "- Thằng con trai của họ… chắc là nó bằng tuổi bé Dudley nhà mình, phải không em?\n"
                   "Bà Dursley nhấm nhẳn:\n"
                   "- Có lẽ\n"
                   "- Nó tên gì? Howard phải không?\n"
                   "- Harry. Một cái tên tầm thường xấu xí.\n"
                   "- Ờ, xấu thật. Anh hoàn toàn đồng ý với em.\n"
                   "Ông không nói thêm lời nào nữa về đề tài này khi cả hai lên lầu vào phòng ngủ. Trong khi bà Dursley vào buồn tắm, ông Dursley đứng bên cửa sổ nhìn ra vườn. Con mèo vẫn còn đó. Nó đang chăm chu ngóng ra đường Privet Drive như thể đang chờ đợi cái gì vậy.\n"
                   "Hay là ông chỉ tưởng tượn ra mọi thứ? Tất cả những chuyện vớ vẩn này thì có liên quan gì tới gia đình Potter nào? Nếu có… nếu mà có dính dáng với cặp phù… Oâi, nghĩ tới đó ông đã cảm thấy không chịu nổi.\n"
                   "Ông bà Dursley lên giường ngủ. Bà Dursley ngủ ngay tức thì, còn ông Dursley thì cứ nằm trăn trở mãi. Cuối cùng một ý nghĩ dễ chịu đã giúp ông ngủ thiếp đi, ấy là nếu mà gia đình Potter có dính dáng đến tất cả những chuyện nhảm nhí ấy thì họ cũng không có lý do gì để dây dưa đến gia đình ông. Gia đình Potter biết rất rõ bà Dursley nghĩ như thế nào về họ và bọn người như họ. Ông Dursley thấy không có lý do gì để mình và vợ mình có thể bị khổ sở về những gì đang diễn ra – Ông ngáp và trở mình – Chuyện đó không thể nào ảnh hưởng đến họ.\n"
                   "Nhưng ông đã lầm.\n"
                   "Ông Dursley cuối cùng cũng có thể tóm được giấc ngủ, dù một cách khó khăn. Nhưng con mèo ngồi trên bờ tường ngoài thì không tỏ vẻ gì buồn ngủ cả. Nó cứ ngồi bất động, mắt đăm không chớp về góc đường Privet Drive. Nó không động đậy ngay cả khi có tiếng cửa xe đóng sầm bên kia đường. Không nhúc nhích ngay cả khi có hai con cú vụt qua phía trên đầu. Và chính xác là đến gần nữa đêm con mèo ấy mới nhúc nhích.\n"
                   "Ấy là lúc một ông già xuất hiện ở góc đường mà con mèo đang ngóng về. Cụ xuất hiện thình lình và lặng lẽ như thể từ mặt đất chui lên. Đuôi con mèo nhẹ ve vẩy và mắt nó nhíu lại.\n"
                   "Xưa nay trên đường Privet Drive chưa từng có một người nào trông kỳ quái như cụ già ấy lại qua. Cụ ốm, cao, rất già, căn cứ vào mái tóc và chòm râu bạc phơ dài đến nỗi cụ phải giắt chúng vô thắt lưng. Cụ mặc áo thụng dài, khoát áo trùm màu tím cũng dài quét đất, mặc dù cụ đã mang đôi giày bốt cao gót lêu nghêu. Đôi mắt xanh lơ của cụ sáng rỡ và lấp lánh phía sau cặp kính có hình dạng nữa vành trăng. Mũi cụ thì vừa dài vừa khoằm như thể cụ đã từng bị gãy mũi ít nhất hai lần. Tên cua cụ là Albus Dumbledore.\n"
                   "Albus Dumbledore dường như không nhận thấy là mình đã đến con đường mà từ tên họ cho đến đôi bốt của cụ không hề được hoan nghênh chào đón. Cụ đang bận lục lọi trong chiếc áo trùm của cụ, tìm kiếm cái gì đó. Rồi đột nhiên, có vẻ như cụ nhận ra là mình đang bị quan sát, bởi vì cụ thình lình ngước nhìn lên con mèo vẫn đang ngó cụ từ bờ tường nhà Dursley. Aùnh mắt của con èmo có vẻ làm cụ thích thú. Cụ chắc lưỡi lẩm bẩm:\n"
                   "- Lẽ ra mình phải biết rồi chứ!\n"
                   "Cụ đã tìm được cái mà cụ lục lọi nãy giờ trong chiếc áo trùm. Nó giống như cái bật lửa bằng bạc. Cụ giơ nó lên cao và bấm. Ngọn đèn đường gần nhất tắt phụt. Cụ bấm lần nữa, ngọn đèn đường kế tiếp tắt ngấm. Cụ bấm mười hai lần như thế, cho đến khi ánh sáng còn lại trên cả con đường chỉ còn là hai đốm sáng long lanh ở phái xa – đó là hai con mắt mèo đang nhìn cụ. Nếu bây giờ mà có ai nhìn qua cửa sổ ra đường, thì dù có con mắt tọc mạch như bà Dursley cũng chịu, không thể thấy được cái gì đang xảy ra. Cụ Albus Dumbledore cất cái tắt – lửa vào áo trùm và đi về phía ngôi nhà số 4 đường Privet Drive. Cụ ngồi xuống trên bờ tường, cạnh con mèo. Cụ không nhìn nó, nhưng được một lúc, cụ nói: “Thật là hay khi gặp bà ở đây đấy, giáo sư McGonagall!”\n"
                   "Cụ quay sang để mỉm cười với con mèo, nhưng chẳng còn mèo nào cả. Thay vì vậy cụ đang mỉm cười với một bà lão trông đứng đắn, đeo kính gọng vuông y như cái dấu vuôn quanh mắt con mèo. Bà cũng khoác áo trùm, màu ngọc bích. Tóc bà bới thành một búi chặt. Bà có vẽ phật ý rõ rệt:\n"
                   "- Làm sao ông biết con mèo đấy là tôi?\n"
                   "- Thưa bà giáo sư yêu quý của tôi, hồi nào tới giờ tôi chưa từng thấy một con mèo nào ngồi cứng đờ như thế.\n"
                   "Giáo sư McGonagall nói:\n"
                   "- Ông mà ngồi cả ngày trên bờ tường thì ông cũng cứng đờ thế thôi.\n"
                   "- Cả ngày?trong khi lẽ ra bà đang phải mở tiệc ăn mừng chứ? Trên đường đến đây, tôi đã gặp ít nhất cả chục đám tiệc tùng linh đình rồi.\n"
                   "Giáo sư McGonagall hít hơi một cách giận giữ và nói một cách không kiên nhẫn:\n"
                   "- Vâng, mọi người ăn mừng, được thôi. Đáng lẽ ông phải thấy là họ nên cẩn thận một chút chứ – ngay ca dân Muggles cũng nhận thấy có chuyện gì đó đang xảy ra. Họ thông báo trong chương trình thời sự đấy.\n"
                   "Bà hất đầu về phía cửa sổ phòng khách tối om của gia đình Dursley.\n"
                   "- Tôi nghe hết.Những đàn cú… sao băng… Chà, họ không hoàn toàn ngu ngốc cả đâu. Họ đã nhận ra có điều gì đó. Sao băng… Tôi cá đó là trò của Diggle, hắn thật chẳng có đầu óc gì cả.\n"
                   "Albus Dumbledore nhẹ nhàng bảo:\n"
                   "- Bà không thể trách như vậy được. Đã mười một năm nay chúng ta chẳng có dịp nào để vui mừng mà!\n"
                   "Giáo sư McGonagall vẫn cáu kỉnh:\n"
                   "- Tôi biết. Nhưng đó không phải là lý do để phát điên lên. Đám đông cứ nhởn nhơ tụ tập bừa bãi trên đường phố giữa ban ngày, thậm chí không thèm mặc quần áo của dân Muggle để ngụy trang, lại còn bàn tán ầm ĩ.\n"
                   "Bà liếc sang cụ Albus Dumbledore ngồi bên, như thể hy vọng cụ sẽ nói với bà điều gì, nhưng cụ không nói gì cả, nên bà nói tiếp:\n"
                   "- Giá mà khi kẻ – mà – ai – cũng – biết – là – ai – đấy biến đi hẳn, người Muggle mới phát hiện ra chúng ta thì hay biết mấy. Nhưng tôi không chắc là hắn đã chết thật chưa hả ông Dumbledore?\n"
                   "- Chắc chắn như vậy rồi. Thật là phước đức cho chúng ta! Bà có dùng giọt chanh không?\n"
                   "- Giọt gì?\n"
                   "- Giọt chanh. Đó là một loại keo của dân Muggle mà tôi rất khoái.\n"
                   "- Không cám ơn.\n"
                   "Giáo sư McGonagall lạnh lùng từ chối, bà không nghĩ là nhấm nháp kẹo lúc này lại thích hợp.\n"
                   "- Như tôi nói đấy, ngay cả nếu như kẻ – mà – ai – cũng – biết – là – ai – đấy đã biến…\n"
                   "- Ôi, giáo sư yêu quý của tôi, một người có đầu óc như bà có thể gọi hắn bằng tên cúng cơm chứ? Mớ bá láp kẻ – mà – ai – cũng – biết – là – ai – đấy thiệt là nhảm nhí. Mười một năm nay tôi đã chẳng bảo mọi người cứ gọi hắn đúng theo tên của hắn: Voldemort sao?\n"
                   "Giáo sư McGonagall e dè nhnìn quanh. Nhưng cụ Dumbledore có vẻ như chẳng để ý gì, cụ đang chăm chú gỡ hai viên kẹo dính nhau và cụ nói tiếp:\n"
                   "- Nếu mà chúng ta cứ gọi bằng: kẻ – mà – ai – cũng – biết – là – ai – đấy thì mọi sự cứ rối beng lên. Tôi thấy chẳng có gì để sợ khi gọi bằng tên cúng cơm của Voldemort.\n"
                   "Giáo sư McGonagall nói, giọng nữa lo lắng nữa ngưỡng mộ:\n"
                   "- Tôi biết ông không sợ. Nhưng ông thì khác. Mọi người đều biết ke û- ma ø- ai – cũng – biết – là… thôi được, goi là Voldemort đi, hắn chỉ sợ có mỗi mình ông mà thôi.\n"
                   "Cụ Albus Dumbledore bình thản nói:\n"
                   "- Bà tâng bốc tôi quá. Voldemort có những quyền lực tôi không bao giờ có.\n"
                   "- Ấy là chỉ bởi vì ông… ừ, ông quá cao thượng nên không xài tới những quyền lực đó.\n"
                   "- Cũng may là trời tối nhé. Kể cũng lâu rồi tôi chưa đỏ mặt, từ cái lần bà Pomfrey nói bả khoái cái mũ trùm tai của tôi.\n"
                   "Giáo sư McGonagall liếc cụ Dumbledore một cái sắc lẻm.\n"
                   "- Mấy con cú lượn vòng vòng chỉ chờ tung tin vịt đấy. Ông biết mọi người đang nói gì không? Về vì sao hắn phải biến đi ấy? Về cái điều đã chặn đứng được hắn ấy?\n"
                   "Có vẻ như giáo sư McGonagall đã gạt tới điểm then chốt mà bà muốn tranh luận. Đó là lý do khiến bà đã phải ngồi chờ suốt cả ngày trên bờ tường cứng và lanh lẽo này. Rõ ràng là chuyện mà mọi người đang bàn tán, cho dù làchuyện gì đi nữa, bà cũng không vôi tin cho đến khi Dumbledore nói với bà là chuyện đó có thật. Tuy nhiên cụ Dumbledore vẫn đang bận lựa một viên kẹo khác chứ không trả lời.\n"
                   "- Chuyện mà họ đang bàn tán ấy,” bà McGonagall nhấn mạnh, “là tối hôm qua Voldemort đã đến Hố Thần. Hắn đi tìm gia đình Potter. Nghe đồn rằng vợ chồng Potter đã… đã…, họ đồn thôi, đã… chết rồi!\n"
                   "Cụ Dumbledore cúi đầu. Giáo sư McGonagall há hốc miệng, ngẹn ngào:\n"
                   "- Vợ chồng Potter… Tôi không thể tin được… Tôi không muốn tin… Ôi, ông Dumbledore…\n"
                   "Cụ Dumbledore duỗi tay vỗ nhê lên vai bà giáo sư, cụ chậm rãi nói:\n"
                   "- Tôi biết… Tôi biết…\n"
                   "Giọng giáo sư McGonagall run run tiếp tục:\n"
                   "- Mà chuyện chưa hết. Họ còn nói hắn tìm cách giết cả đứa con trai của Potter, bé Harry ấy. Nhưng… hắn không giết được> Hắn không thể giết nổi đứa bé. Không ai biết tại sao, thế nào…, nhưng họ nói… khi không thể giết được Harry Potter, quyền lực của Voldemort bị tiêu tan. Chính vì vậy mà hắn cũng phải biến đi.\n"
                   "Cụ Dumbledore buồn bã gật đầu. Giáo sư McGonagall ấp úng:\n"
                   "- Chuyện đó… đó… là… là… thật sao? Hắn đã làm bao nhiêu chuyện tai quái, giết chết bao nhiêu người.. mà…, mà rốt cuộc hắn không thể giết nỗi một thằng bé? Thật là không tin được… cái gì đã chặn nổi bàn tay hắn như vậy… Nhưng bằng cách nào mà Harry Potter sống sót?\n"
                   "Cụ Dumbledore nói:\n"
                   "- Chúng ta chỉ có thể đoán mò mà thôi. Chuyện ấy chẳng bao giờ biết được chính xác.\n"
                   "Giáo sư McGonagall rút ra một cái khăn tay chùi nước mắt dưới cặp mắt kính. Cụ Dumbledore thở dài một tiếng rõ to khi rút chiếc đồng hồ vàng trong túi ra xem xét. Cái đồng hồ ấy cũ lắm. Nó có mười hai kim nhưng không có số. Thay vào những con số là các hành tinh nho nhỏ di chuyển quanh mép đồng hồ. Nhưng chắc là cụ Dumbledore coi giờ được bằng cái đồng hồ đó, nên khi nhét nó lại vào trong túi, cụ nói:\n"
                   "- Hagrid đến trễ. Chắc chính lão nói cho bà biết là tôi đến đây, đúng không?\n"
                   "- Đúng.\n"
                   "Giáo sư McGonagall xác nhận và nói tiếp:\n"
                   "- Chắc ông cũng không thèm nói cho tôi biết tại sao ông đến đây chứ?\n"
                   "- Tôi đến đây để giao Harry Potter cho dì dượng nó. Bây giờ nó chỉ còn có họ là bà con.\n"
                   "Giáo sư McGonagall nhảy dựng lên, chỉ tay vào ngôi nhà số 4:\n"
                   "- Ông nói gì? Chắc là ông không có ý nói đến mấy người sống trong đó chứ? Dumbledore, ông không thể làm vậy. Tôi đã quan sát họ suốt cả ngày. Ông không thể tìm ra được người nào khá hơn họ hay sao? Mà họ cũng đã có một đứa con trai. Tôi đã nhìn thấy thằng nhóc ấy, nó đá mẹ nó suốt quãng đường đến tiệm bánh kẹo, khóc la vòi vĩnh cho được mấy viên kẹo. Harry Potter mà phải đến sống ở đây sao?\n"
                   "Cụ Dumbledore khẳng định:\n"
                   "- Đây là nơi tốt nhất cho đứa bé. Khi nó lớn lên dì dượng của nó có thể giải thích cho nó hiểu. Tôi đã viết cho họ một lá thư.\n"
                   "- Một lá thư?\n"
                   "Giáo sư McGonagall lập lại yếu ớt, thả người ngồi xuống bờ tường, băn khoăn nói tiếp:\n"
                   "- Ông Dumbledore, ông thật sự tin là ông có thể giải thích mọi chuyện trong một lá thư à? Mấy người đó sẽ không bao giờ hiểu đứa bé! Nó sẽ nổi tiếng - như một huyền thoại. Tôi sẽ không ngạc nhiên nếu sau này người ta gọi ngày hôm nay là ngày Harry Potter: sẽ có sách viết về Harry. Mọi đứa trẻ trong thế giới chúng ta rồi sẽ biết đến tên nó!\n"
                   "- Đúng vậy.\n"
                   "Cụ Dumbledore nhướn mắt dòm qua đôi kính nữa vành trăng của cụ một cách nghiêm túc nói rằng:\n"
                   "- Nhiêu đó cũng đủ hại đầu óc bất cứ đứa trẻ nào. Nổi tiếng trước cả khi biết đi biết nói! Nổi tiếng về những điều mà nó cũng không thể nhớ được! Bà không thấy là tốt cho nó hơn biết bao nếu nó lớn lên ngoài vòng bao phủ của tiếng tăm, lớn lên một cách bình thường cho đến khi nó đủ lớn để làm chủ được điều đó sao?\n"
                   "Giáo sư McGonagall lại há hốc miệng thay đổi ý kiến, nuốt vô, ngậm miệng lại rồi nói:\n"
                   "- Vâng, vâng, dĩ nhiên là ông nói đúng. Nhưng mà ông Dumbledore ơi, làm sao đứa bé đến đây được?\n"
                   "Bà giáo sư nhìn chòng chọc vào tấm áo trùm của cụ Dumbledore như thể là bà nghĩ cụ đang giấu đứa bé trong đó. Cụ Dumbledore nói:\n"
                   "- Hagrid đang mang nó đến.\n"
                   "- Ông cho là giao lão Hagrid một viêc quan trọng như thế này là khôn ngoan sao?\n"
                   "- Tôi có thể giao cả đời tôi cho Hagrid.\n"
                   "Bà McGonagall vẫn không bằng lòng:\n"
                   "- Tôi không nói là lão Hagrid không biết phải quấy, nhưng mà ông cũng biết đấy, lão là chúa ẩu… Uûa? Cái gì vậy?\n"
                   "Một tiếng động trầm trầm nổi lên quanh họ, nghe rầm rầm, càng lúc càng lớn. Cả hai nhìn ra đường xem có ánh đèn xe không, thế rồi những tiếng động nghe như sấm dội khiến cả hai người ngước nhìn lên trời: một chiếc xe gắn máy khổng lồ chạy trên không trung rồi hạ xuống, lăn bánh trên mặt đường nhựa trước mặt họ.\n"
                   "Nếu cái xe gắn máy bự quá khổ, thì cũng không thấm gì so với người ngồi trên xe. Lão hầu như cao gấp đôi người bình thường và bự có đến gấp năm, nếu tính chiều ngang. Trông lão ta to lớn đến nỗi khó tin, và lại hoang dã. Những nùi tóc râu đen thui hầu như che kín gương mặt lão, tay lão trông như cần cẩu, còn chân thì ú na ú núc như mính con cá heo con. Trên đôi tay vạm vỡ ấy là một nùi chăn tả. Cụ Dumbledore tỏ ra yên tâm, bảo:\n"
                   "- Hagrid, cuối cùng anh đã đến. Anh kiếm đâu ra cái xe đó?\n"
                   "Lão khổng lồ cẩn thận trèo xuống xe đáp:\n"
                   "- Kính thưa ngài giáo sư Dumbledore, tôi mượn của Sirius Đen. Thưa ngài, tôi đã mang được cậu bé đến đây.\n"
                   "- Có lôi thôi rắc rối gì không?\n"
                   "- Thưa ngài không ạ. Ngôi nhà hầu như tan hoang, nhưng tôi đã kịp đem nó ra trước khi dân Muggle bắt đầu lăng xăng chung quanh. Đang bay tới đây thì nó lăn ra ngủ.\n"
                   "Cụ Dumbledore và giáo sư McGonagall cúi xuống đống chăn tã. Bên trong mớ chăn ấy là đứa bé đang ngủ say. Trên vầng trán đứa bé có một vết thương nhỏ hình tia chớp. Giáo sư McGonagall thì thầm:\n"
                   "- Có phải đó là…\n"
                   "- Phải, nó sẽ mang vết thẹo đó suốt đời.\n"
                   "- Ông không thể xoá nó đi sao ông Dumbledore?\n"
                   "- Nếu mà tôi làm được thì tôi cũng chẳng đời nào làm. Thẹo cũng có lúc xài đến. Tôi đây cũng có một cái thẹo ở trên đầu gối, nó có giá trị như cái bảng đồ đường xe điện ngầm ở Luân – Đôn ấy. Thôi, Hagrid, đặt nó ở đây, chúng ta nên làm xong chuyện này cho rồi.\n"
                   "Cụ Dumbledore bồng Harry đi về phía nhà Dursley. Lão Hagrid ấp úng:\n"
                   "- Tôi… tôi có thể hôn tạm biệt đứa bé được không ạ?\n"
                   "Lão cuối cái đầu lông lá bờm xờm xuống mặt đứa bé và dụi mớ râu ria lởm chởm của lão lên làng da non của đứa bé. Rồi thình lình lão Hagrid thốt lên một tiếng như tiếng chó bị thương. Giáo sư McGonagall vội nhắc nhở:\n"
                   "- Xuỵt! Lão đánh thức đám Muggle bây giờ.\n"
                   "Lão Hagrid thổn thức:\n"
                   "- Xin lỗi, hic hic. Nhưng tôi không thể… Hic hic. Vợ chồng Potter chết rồi, và Harry bé bỏng phải đi ở nhờ dân Muggle. Hic hic.\n"
                   "Giáo sư McGonagall vỗ về:\n"
                   "- Vâng, vâng, buồn lắm, nhưng mà ráng nín khóc đi, Hagrid, không thôi bọn mình bị lộ đấy.\n"
                   "Lão Hagrid cố dằn cảm xúc, đứng bên giáo sư McGonagall, nhìn theo cụ Dumbledore bồng Harry Potter đi qua sân vườn đến cửa trước nhà Dursley, nhẹ nhàng đặt đứa bé xuống bật cửa, lấy trong áo trùm ra một lá thư, nhét lá thư dưới lớp chăn quấn quanh đứa bé, rồi trở lại với hai người kia. Cả ba đứng lặng cả phút nhìn cái bọc chăn tả đang ấp ủ đứa bé. Vai của Hagrid run lên từng chập, mắt của giáo sư McGonagall chớp chớp liên tục, và cái tia sáng lấp lánh thường loé lên từ đôi mắt của cụ Dumbledore cũng dường như tắt ngóm. Cuối cùng cụ Dumbledore nói:\n"
                   "- Thôi, đành thế. Chúng ta chẳng còn việc gì ở đây nữa. Có lẽ chúng ta đi nhập tiệc với những người khác thôi.\n"
                   "- Dạ. –Tiếng lão Hagrid đáp rõ to. – Tôi sẽ đem trả lại Sirius cái xe này. Chào giáo sư McGonagall, và xin chào ngài, giáo sư Dumbledore.\n"
                   "Chùi nước mắt còn đang chảy ròng ròng trên mặt, lão Hagrid nhảy lên xe và đạp một cái cật lực cho máy nổ, rồi lão rú ga phóng vào không trung đen như hũ nút.\n"
                   "Cụ Dumbledore cuối đầu chào bà McGonagall:\n"
                   "- Tôi mong sớm gặp lại bà, giáo sư McGonagall.\n"
                   "Giáo sư McGonagall hỉ mũi một cái để đáp lễ. Cụ Dumbledore xoay người bước xuống đường. Tới góc đường, cụ dừng bước, lấy trong áo trùm ra cái tắc - lửa bằng bạc. Cụ giơ lên bấm nó một cái, rồi mười hai cái, lập tức mười hai cái bóng đèn trên đường Privet Drive bật sáng, nhưng cũng không kịp soi bóng một con mèo hoang to tướng chuồn lẹ đằng sau khúc quanh ở phía đầu kia con đường.\n"
                   "Còn lại một mình, cụ Dumbledore nhìn lần cuối cái bọc chăn tả trên bậc cửa ngôi nhà số 4. Cụ ngậm ngùi nói:\n"
                   "- Chúc cháu may mắn, Harry.\n"
                   "Rồi phất tấm áo trùm một cái cụ biến mất.\n"
                   "Một luồn gió thoảng qua những hàng rào cây xanh của ngôi nhà trên đường Privet Drive. Ngôi nhà ngăn nắp và những hàng rào cắt xén ngay ngắn ấy là nơi cuối cùng mà người ta có thể mong đợi một chuyện kỳ lạ xảy ra. Harry Potter trở mình trong cuộn chăn mà không thức giấc. Một nắm tay nhỏ xíu của bé đặt trên lá thư sát bên mình, và bé ngủ tiếp, không hề biết là vài tiếng đồng hồ nữa bà Dursley sẽ đánh thức bé dậy bằng một tiếng hét thảng thốt khi bà mở cửa để bỏ những vỏ chai sữa rỗng. Đứa bé cũng không biết là mình sẽ trở thành món đồ chơi của thằng anh họ Dudley, bi nó tha hồ ngắt véo trong vài tuần lễ sau đó. Đứa bé không hề biết gì về những điều đó trong lúc này, cái lúc này mà khắp nơi trên cả nước, tiệc tùng linh đình đang diễn ra, người người đều nâng ly chúc tụng: “Uống mừng Harry Potter! Đứa bé vẫn sống!”"',
     'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2016%2F09%2F9781408855652-png.jpg',
     'The first novel in the Harry Potter series and Rowling\'s debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry.',
1683007258510,
1683007258510),
(2,
'Harry Potter 2',
"Đây không phải là vụ cãi vã đầu tiên nổ ra trong buổi điểm tâm ở nhà số 4 đường Privet Drive. Hồi sáng sớm tinh sương này, ông Vernon Dursley đã bị đánh thức vì một tiếng cú rúc inh tai phát ra từ căn phòng thằng cháu Harry của ông.\n"
"Ông gầm lên từ phía đầu bàn ăn:\blogsn"
"- Lần thứ ba trong tuần này rồi đó nghen! Mày mà không kềm được con cú đó thì phải tống nó ngay đi cho tao!\n"
"Một lần nữa, Harry lại phải cố gắng giải thích:\n"
"- Tại nó chán quá đó, dượng. Nó quen bay nhảy bên ngoài. Nếu dượng cho phép cháu thả nó ra đêm nay…\n"
"Dượng Vernon nạt một tiếng, trứng chiên văng ra dính cả vào bộ ria mép rậm rạp của dượng:\n"
"- Bộ tao ngu lắm hả? Tao thừa biết chuyện gì xảy ra nếu thả con cú đó chớ…\n"
"Ông ném cho vợ, dì Petunia, một cái nhìn tăm tối.\n"
"Harry toan cãi lại, nhưng tiếng nói của nó bị nhậm chìm một tiếng ợ to và dài của Dudley nhấn chìm:\n"
"- Con muốn ăn thêm thịt muối chiên.\n"
"Dì Petunia hướng đôi mắt mơ màng về phía cậu con đồ sộ:\n"
"- Còn nhiều trong chảo đó cưng! Hễ có dịp là mẹ phải bồi dưỡng cho con… chớ mẹ không ưa được đồ ăn ở trường…\n"
"- Nhảm nhí, anh chưa bao giờ bị đói khi anh còn theo học trường Smeltings.\n"
"Dượng Vernon hăng hái ngắt lời vợ, rồi ông quay sang con trai:\n"
"- Còn đủ cho con ăn no mà, phải không con trai của ba?\n"
"Dudley vốn đã to đến nỗi mông của nó bè ra cả hai bên chiếc ghế nhà bếp. Nó nhe răng cười với ba nó rồi quay sang Harry bảo:\n"
"- Đưa cái chảo!\n"
"Harry bực mình:\n"
"- Anh quên nói hai chữ nhiệm màu rồi!\n"
"Hiệu quả của câu nói đơn giản này đối với tất cả những người còn lại trong gia đình thật không tin được: Dudley há hốc miệng và té từ trên ghế xuống đánh rầm một cái làm rung rinh cả nhà bếp; bà Dursley hét lên một tiếng nhỏ và đưa hai tay bụm miệng mình; còn ông Dursley thì đứng phắt dậy, mạch máu nổi cộm phập phồng bên hai thái dương.\n"
"Harry vội giải thích:\n"
"- Ý con muốn nói hai tiếng “làm ơn”, chứ con không có ý…\n"
"Nhưng dượng đã nổi cơn thịnh nộ, gầm lên, nước miếng phun khắp bàn:\n"
"- TAO ĐÃ DẠY MÀY CÁI GÌ VỀ VIỆC NÓI HAI TIẾNG “NM” ẤY TRONG NHÀ TAO HẢ?\n"
"- Nhưng con…\n"
"Dượng đấm xuống bàn một cái, rống lên:\n"
"- SAO MÀY DÁM LÀM CHO DUDLEY SỢ HẢ?\n"
"\n"
"\n"
"- Con chỉ…\n"
"- TAO CẢNH CÁO MÀY! TAO KHÔNG CHỊU ĐƯỢC BẤT CỨ BIỂU HIỆN BẤT BÌNH THƯỜNG NÀO CỦA MÀY DƯỚI MÁI NHÀ NÀY.\n"
"Harry nhìn sững hết gương mặt tím rịm của dượng Vernon đến gương mặt tái mét của dì Petunia. Dì đang cố gắng đỡ Dudley đứng lên.\n"
"- Dạ… dạ. – Harry nói – Thôi được…\n"
"Dượng Vernon ngồi xuống, thở phì phì như con tê giác lên giây thiều, và ngó Harry qua khóe mắt nhỏ sắc lẻm của ông.\n"
"Kể từ hồi Harry về nhà nghỉ hè, dượng Vernon đẽ đối xử với nó như một trái bom có thể nổ bất cứ lúc nào, bởi vì Harry không phải là một đứa trẻ bình thường. Nói nào ngay, Harry không thể bình thường như dượng mong muốn được.\n"
"Dượng Vernon thì to bè và không có cổ, chỉ có một bộ ria mép vĩ đại.\n"
"Harry Potter là một phù thủy – một phù thủy mới toanh vừa học xong năm thứ nhất ở Hogwarts, học viện pháp thuật và ma thuật. Và nếu gia đình Dursley không vui vẻ gì khi phải đón tiếp nó về nghỉ hè ở nhàhọ, thì điều đó cũng chẳng thấm gì với nỗi buồn đang gậm nhấm Harry.\n"
"Nó nhớ trường Hogwarts tha thiết như bị đau bao tử kinh niên. Nó nhớ tòa lâu đài với những hành lang bí mật và những con ma, nhớ những lớp học (mặc dù có lẽ không nhớ lắm bậc thầy Độc dược Snape). Nó nhớ bầy cú đưa thư mỗi sáng, nhớ bàn ăn dài trong Đại Sảnh đường, cái giường ngủ giữa bốn tấm áp phích trong tháp ký túc xá. Nhớ những buổi đến thăm bác Hagrid – người giữ khóa – trong căn chòi của bác cạnh khu Rừng Cấm. Và nó đặc biệt nhớ Quidditch, môn thể thao phổ biến nhất trong thế giới phù thủy (có sáu cột gôn cao, bốn trái banh bay, và mười bốn cầu thủ cỡi chổi thần).\n"
"Dì Petunia thì mặt dài như mặt ngựa, người xương xẩu.\n"
"Tất cả sách thần chú của Harry, cả cây đũa phép, áo chùng phù thủy, cái vạc, và cây chổi thượng hạng Nimbus 2000, đều bị dượng Vernon khóa kỹ trong tú xép dưới gầm cầu thang ngay cái lúc mà Harry vừa đặt chân trở về. Gia đình Dursley thì bận tâm gì chuyện Harry có thể mất chỗ trong đội Quidditch nhà Gryffindor vì nó không luyện tập gì hết suốt mùa hè? Và nếu Harry trở về trường Hogwarts nhập học mà không làm xong bài tập nào hết thì có ăn nhằm gì đến nhà Dursley?\n"
"Gia đình Dursley là những người mà giới phù thủy gọi là Muggle (những người không có tới một giọt máu phù thủy trong huyết quản), và theo quan điểm của ông bà Dursley thì có một phù thủy trong nhà là cả một mối nhục sâu sắc nhất. Dượng Vernon còn nhốt cả con cú của Harry, con Hedwig, trong lồng và khóa lại, không cho nó đưa thư cho bất cứ ai trong thế giới phù thủy.\n"
"Harry không giống ai trong cái gia đình này. Dượng Vernon thì to bè và không có cổ, chỉ có một bộ rua mép đen vĩ đại; dì Petunia thì mặt dài như mặt ngựa, người xương xẩu; Dudley thì tóc vàng, da hồng, và phục phịch. Trong khi Harry thì nhỏ và gầy, đôi mắt xanh lá cây rất sáng và mái tóc đen huyền luôn luôn rối bù. Nó đeo kính tròn, và trên trán nó có một vết thẹo mỏng hình tia chớp.\n"
"Chính vết thẹo này đã làm cho Harry trở thành đặc biệt, ngay cả đối với một phù thủy thì đó cũng là một điều rất đặc biệt: vết thẹo đó dấu chỉ duy nhất về quá khứ bí ẩn của Harry, về lý do mà Harry được đem bỏ ở thềm nhà Dursley hơn mười một năm trước.\n"
"Năm vừa lên một, không hiểu bằng cách nào đó, Harry đã sống sót được dưới phù phép của tên phù thủy Hắc ám vĩ đại nhất của mọi thời đại – Ngài Voldermort – một cái tên mà hầu hết phù thủy vẫn còn sợ hãi khi nhắc đến. Cha mẹ của Harry đã bị Voldermort giết chết, nhưng Harry sống sót với vết thẹo hình tia chớp, và – không ai hiểu tại sao – quyền lực của Voldermort bị tiêu tan ngay khoảnh khắc mà hắn không giết được Harry.\n"
"Từ đó Harry được dì dượng nuôi lớn. Nó sống với gia đình Dursley trong suốt mười năm, không hề hiểu tại sao nó cứ gây ra bao nhiêu điều kỳ lạ, mặc dù nó không cố ý; và nó cũng tin vào câu chuyện mà gia đình Dursley đã nói với mình, rằng cái thẹo nó có là trong một tai nạn xe hơi làm cho ba má nó chết.\n"
"Thế rồi, cách đây đúng một năm, trường Hogwarts gởi thư cho Harry, khiến cho toàn bộ câu chuyện này được phơi bày. Rồi Harry theo học trường Hogwarts, tại đây, Harry và cái thẹo của mình đã trở thành rất nổi tiếng… Nhưng bây giờ năm học đã qua, nó phải trở về với gia đình Dursley để nghỉ hè, lại bị đối xử như một con chó ghẻ.\n"
"Gia đình Dursley thậm chí không thèm nhớ hôm nay là sinh nhật thứ mười hai của Harry. Dĩ nhiên Harry cũng chẳng trông mong gì nhiều; họ cũng chưa từng cho nó một món quà thực sự nào, đừng nói chi tới bánh sinh nhật. Nhưng mà hoàn toàn không đếm xỉa gì hết trơn thì…\n"
"Lúc đó, dượng Vernon tằng hắng lấy giọng một cách long trọng và nói:\n"
"- Nghe đây, như mọi người đều biết, hôm nay là một ngày rất quan trọng.\n"
"Harry ngẩng đầu lên, không dám tin nổi.\n"
"Dượng Vernon nói:\n"
"- Đây có lẽ là ngày mà ta đạt được sự thăng tiến lớn trong nghề nghiệp của ta từ trước tới nay.\n"
"Harry ngó trở xuống miếng bánh mì nướng của nó. Thì ra, nó nghĩ một cách cay đắng, dượng Vernon đang nói về cái bữa dạ tiệc ngu xuẩn ấy. Suốt hai tuần nay ông ấy không hề nói đến cái gì khác hơn. Một nhà xây dựng giàu có nào đó cùng bà vợ của ông ta sẽ đến ăn tối, và dượng Vernon – nhà sản xuất máy khoan – hy vọng kiếm được món đơn đặt hàng lớn của ông này.\n"
"Dượng Vernon nói:\n"
"- Anh nghĩ chúng ta nên coi lại hết chương trình một lần nữa. Đúng tám giờ tất cả chúng ta nên ở đúng vị trí của mình. Petunia, em sẽ đứng ở…\n"
"- … trong phòng khách, chờ đón những vị khách quí đến nhà chúng ta. – Dì Petunia tiếp lời ngay.\n"
"Dượng Vernon hài lòng:\n"
"\n"
"\n"
"- Tốt, tốt, còn Dudley?\n"
"- Con sẽ chờ để mở cửa.\n"
"Dudley đáp và nở một nụ cười điệu đàng giả tạo:\n"
"- Thưa ông bà Mason, cho phép con cất áo khoác của ông bà ạ.\n"
"Dì Petunia kêu lên sung sướng:\n"
"- Họ sẽ mê thằng bé cho coi!\n"
"- Xuất sắc, Dudley!\n"
"Dượng Vernon khen con trai xong quay qua Harry:\n"
"- Còn mày?\n"
"Harry đáp bằng giọng nhạt phèo:\n"
"- Con sẽ ở trong phòng ngủ, không được làm ồn và giả đò như không có mặt vậy.\n"
"- Đúng vậy! – Giọng dượng Vernon thật ác.\n"
"- Anh sẽ dắt họ đi vào phòng khách, giới thiệu với em, Petunia, và em sẽ rót rượu mời họ. Lúc tám giờ mười lăm…\n"
"Dì Petunia tiếp lời chồng:\n"
"- Em sẽ mời khách dùng cơm tối.\n"
"- Và Dudley, con sẽ nói…\n"
"- Thưa bà Mason, cho phép cháu đưa bà vào phòng ăn?\n"
"Dudley vừa nói vừa đưa cánh tay ú núc ra cho người đàn bà vô hình.\n"
"Dì Petunia hít hà:\n"
"- Ôi, trang quân tử hoàn hảo bé bỏng của mẹ!\n"
"- Còn mày?\n"
"Dượng Vernon nạt Harry. Nó nhai lại một cách chán ngắt:\n"
"- Con sẽ ở trong phòng ngủ, không được làm ồn và giả đò như không có mặt vậy.\n"
"- Đúng. Bây giờ chúng ta dợt trước vài lời khen ngợi trong bữa tiệc. Petunia, em có ý kiến gì?\n"
"- Thưa ông Mason, anh Vernon nói với tôi ông là một người chơi gôn tuyệt vời… Bà Mason, xin bà chỉ dùm tôi nơi bà mua cái áo đầm này…\n"
"- Tuyệt. Còn Dudley?\n"
"\n"
"- Con nói như vầy nhá: Ở trường chúng cháu phải viết một bài luận văn về người anh hùng của mình, và thưa ông Mason, cháu viết về ông ạ.\n"
"Thế này là quá sức chịu đựng của dì Petunia lẫn Harry. Dì Petunia thì òa khóc và ôm nựng cậu con trai vĩ đại của mình, còn Harry thì chuồi xuống gầm bàn để người ta không thấy nó hả họng cười.\n"
"- Còn mày, thằng kia?\n"
"Harry trồi lên, giữ nét mặt nghiêm túc trả bài:\n"
"- Con sẽ ở trong phòng ngủ, không được làm ồn và giả đò như không có mặt vậy.\n"
"- Đúng, cứ làm vậy cho tao.\n"
"Giọng dượng Vernon đầy dọa nạt.\n"
"- Ông bà Mason không biết chút gì về mày và sẽ không bao giờ biết gì về mày cả. Khi bữa tiệc kết thúc, anh sẽ đưa bà Mason trở lại phòng khách uống cà phê, Petunia à, và anh sẽ dẫn dắt đề tài câu chuyện đến những cái máy khoan. Nếu may mắn, anh sẽ ký tên đóng dấu vụ làm ăn này trước bản tin mười giờ tối. Và ngày mai vào giờ này, chúng ta sẽ đi sắm cho căn nhà nghỉ mát nghỉ mát của mình ở Majorca.\n"
"Harry không cảm thấy hào hứng lắm về chuyện này, bởi vì ở Majorca thì gia đình Dursley cũng đâu có ưa nó hơn là khi họ ở số 4 đường Privet Drive.\n"
"- Được rồi… Để anh xuống phố để lấy áo khoác dạ tiệc của anh và Dudley.\n"
"Quay qua Harry, dượng Vernon quát:\n"
"- Còn mày, liệu hồn mà tránh chỗ cho dì mày quét dọn!\n"
"Harry lỉnh ra ngoài bằng cửa sau. Hôm ấy là một ngày nắng ấm rực rỡ. Nó băng qua bãi cỏ, ngồi phịch xuống cái ghế dài kê trong vườn, và hát thầm ình nghe:\n"
"- Chúc tôi một sinh nhật hạnh phúc! Một sinh nhật hạnh phúc cho tôi!\n"
"Chẳng có thiệp, chẳng có quà, và tối nay nó sẽ làm như nó không hề có mặt trên đời. Nó buồn bã nhìn đăm đăm vào bờ giậu. Nó chưa bao giờ cảm thấy cô đơn như vậy. nó nhớ bạn nó, nhớ hơn bất cứ thứ gì khác ở Hogwarts, hơn cả những trận Quidditch. Nó nhớ những đứa bạn thân nhất của nó, Hermione và Ron. Nhưng có lẽ tụi nó không nhớ nó chút nào. Suốt mùa hè, chẳng đứa nào trong hai đứa đó viết thư cho Harry. Ngay cả Ron, đứa từng hứa sẽ mời Harry đến nhà chơi, cũng bặt vô âm tín.\n"
"Đã biết bao nhiêu lần, Harry toan dùng phép thuật tháo cũi sổ lồng cho con Hedwig để nó đem thư đến cho Hermione và Ron. Nhưng nó hiểu là không nên liều chỉ vì một chuyện như vậy. Phù thủy vị thành niên không được pháp dùng pháp thuật ở ngoài trường học. Harry chưa hết nói cho gia đình Dudley biết điều này; bởi nó biết, chính vì họ sợ nó biến họ thành mấy con bọ hung mà họ không dám nhốt nó vô phòng xép dưới gầm cầu thang chung với những đũa phép và chổi thần của nó.\n"
"Hai con mắt màu xanh lá cây to tổ tướng hiện ra giữa đám cây.\n"
"Trong mấy tuần lễ đầu khi Harry mới về nhà, nó khoái giả bộ lẩm nhẩm những câu nhảm nhí vô nghĩa để thấy thằng Dudley, với thân hình phì nhiêu, phóng ra khỏi phòng với tốc độ tối đa. Nhưng sự im lặng kéo dài của Ron và Hermione làm cho Harry cảm thấy nó bị tách biệt ra khỏi thế giới phù thủy đến nỗi mất luôn cả hứng chọc ghẹo Dudley. Và đến hôm nay thì rõ ràng cả Ron và Hermione đều đã quên béng sinh nhật của nó.\n"
"Bây giờ nó sẽ đánh đổi cái gì để có được một bức thư gởi từ Hogwarts? Từ bất cứ một phù thủy nào? Thậm chí bây giờ thấy được hình ảnh của kẻ thù không đội trời chung, Draco Malfoy, nó cũng thấy vui mừng, miễn sao có thể tin chắc rằng tất cả những gì thuộc về Hogwarts không phải chỉ là một giấc mơ…\n"
"Cả niên học qua của nó ở Hogwarts không hẳn toàn chuyện vui. Vào những ngày cuối cùng của niên học, Harry đã phải trực diện chiến đấu với chính Ngài Voldermort chứ không ai khác. Tuy Voldermort chỉ còn là tàn tích của cản thân hắn trước đây, nhưng hắn vẫn còn đáng sợ, vẫn xảo quyệt, vẫn quyết tâm giành lại quyền lực. Harry đã thoát khỏi bàn tay độc địa của Voldermort lần thứ hai, nhưng là thoát chết trong đường tơ kẽ tóc; thậm chí đến bây giờ, nó vẫn choàng thức giấc giữa đêm khuya, vã mồ hôi lạnh, tự hỏi bây giờ Voldermort đang ở đâu. Nó vẫn nhớ gương mặt xá xịt và to tướng của hắn, đôi mắt điên rồ trợn trừng của hắn…\n"
"Bỗng nhiên Harry ngồi dựng đứng trên băng ghế. Nó lơ đãng trừng mắt nhìn bờ giậu trước mặt – và nhận ra cái giậu lại nó chăm chăm. Hai con mắt màu xanh lá cây to tổ tướng hiện ra giữa đám lá cây.\n"
"Harry vừa bật đứng dậy thì một giọng nói giễu cợt vang lên từ bên kia bãi cỏ:\n"
"- Tao biết hôm nay là ngày gì nè!\n"
"Dudley vừa hát vừa đi ục ịch về phía Harry.\n"
"Hai con mắt to nháy một cái rồi biến mất.\n"
"Harry vẫn không dứt mắt khỏi chỗ lúc nãy là hai con mắt của cái giậu cây:\n"
"- Mày nói cái gì?\n"
"Dudley tới sát bên Harry, lặp lại:\n"
"- Tao biết hôm nay là ngày gì nè!\n"
"- Giỏi à. Vậy là cuối cùng mày cũng biết được các ngày trong tuần rồi hả?\n"
"Dudley cười nhạo:\n"
"- Hôm nay là sinh nhật của mày. Mà sao mày chẳng nhận được một tấm thiệp chúc mừng nào vậy? Mày không có đứa bạn nào ở cái trường quỷ ấy hả?\n"
"\n"
"\n"
"Harry nói tỉnh bơ:\n"
"- Tốt hơn là đừng để á mày nghe mày nói về trường tao.\n"
"Dudley kéo quần lên, cái đũng quần cứ xệ xuống dưới cái mông phệ của nó. Nó nghi ngờ hỏi:\n"
"- Sao mày cứ ngó chăm chăm cái bờ giậu vậy?\n"
"Harry nói:\n"
"- Tao đang tính xem dùng câu thần chú nào để đốt cái giậu này thì tốt nhất.\n"
"Tức thì Dudley nhảy bật ra sau, vẻ hoảng sợ hiện trên gương mặt phúng phính của nó.\n"
"- Mày kh… không… Ba nói mày không được làm ph… phép thuật… Ba nói ba sẽ quăng mày ra khỏi nhà… Mà mày thì không có chỗ nào khác để tá túc… mày đâu có bạn bè nào đón về nhà đâu…\n"
"Harry tức giận đọc:\n"
"- Uùm ba la ba xạo ba bự! Tầm bậy tầm bạ! Xí xa xí xồ! Láo ta láo toét!\n"
"Dudley hú lên:\n"
"- MAAAAAÁÁÁ!\n"
"Nó ba chân bốn cẳng chạy lạch bạch vô nhà.\n"
"- MAAA ÁÁÁ! Coi nó làm gì kìa?\n"
"Harry trả giá đắt ột chút đùa vui của nó. Bởi vì cả Dudley lẫn cái hàng giậu không bị tổn thương gì hết, dì Petunia biết là Harry thực ra không có làm phép thuật gì ráo. Nhưng Harry cũng phải thụp đầu tránh cái chảo đầy xà bông mà dì phang vô đầu nó. Rồi dì phạt, bắt nó làm việc, đe rằng nếu nó mà làm không hết việc thì đừng có hòng mà ăn tối.\n"
"Trong khi Dudley lượn qua lượn lại, vừa ăn kem vừa ngó chừng, thì Harry lau cửa sổ, rửa xe hơi, cắt cỏ, tỉa bồn hoa, tưới tỉa bụi hồng, và sơn lại cái băng ghế trong vườn. Mặt trời chói lòa trên đầu, thiêu đốt gáy nó. Harry biết lẽ ra nó không nên đớp cái mồi nhử của Dudley, nhưng Dudley đã đâm trúng nỗi đau trong tim nó, nói ra cái điều đang dày vò nó: có lẽ nó không có người bạn nào ở Hogwarts thật…\n"
"Ước gì họ có thể nhìn thấy Harry Potter nổi tiếng vào lúc này. Harry cay đắng nghĩ, khi nó rải phân trên bồn hoa, lưng nó đau ê ẩm và mồ hôi chảy ròng ròng xuống mặt.\n"
"Cuối cùng, lúc bảy giờ ba mươi, khi nó đã kiệt sức thì nghe có tiếng dì Petunia kêu:\n"
"- Vô đây! Bước trên giấy báo lót sàn nghe không!\n"
"Harry mừng rỡ đi vô dưới mái che của căn bếp sáng choang. Trên đầu tủ lạnh là cái bánh nướng dành cho tối nay: trét đầy kem bơ và một bông hoa tím làm bằng đường. một tảng thịt heo quay to đang xì xèo trong lò nướng.\n"
"Dì Petunia chỉ vô hai lát bánh mì và một nhúm phô mai trên cái bàn nhà bếp, nạt Harry:\n"
"- Ăn lẹ lên! Ông bà Mason sắp đến rồi đó.\n"
"Dì Petunia đã thay sẵn một cái áo đầm dạ tiệc màu hồng.\n"
"Chẳng may, trên giường đã có ai đó ngồi sẵn rồi.\n"
"Harry rửa tay rồi ngốn ngấu bữa ăn tối thảm hại của nó. Canh lúc Harry vừa ăn xong, dì Petunia dọn ngay chiếc dĩa của nó.\n"
"- Lên lầu! Mau lên!\n"
"Khi đi ngang qua phòng khách, Harry kịp thoáng thấy dượng Vernon và Dudley trong bộ áo khoác dạ tiệc, cổ đeo nơ. Nó chỉ vừa mới leo lên hết mấy bậc cầu thang thì chuông cửa reo và gương mặt giận dữ của dượng Vernon xuất hiện ở chân cầu thang.\n"
"- Nhớ nghe chưa oắt con – chỉ một tiếng động thôi là…\n"
"Harry nhón gót đi về phòng ngủ, mở cửa lách vào, đóng cửa rồi quăng mình trên cái giường của nó.\n"
"Chẳng may, trên giường đã có ai đó ngồi sẵn rồi.",
'https://m.media-amazon.com/images/I/81THMAxo+pL._AC_UF1000,1000_QL80_.jpg',
'What is the plot in Harry Potter and the Chamber of Secrets? The plot follows Harry\'s second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school\'s corridors warn that the "Chamber of Secrets" has been opened and that the "heir of Slytherin" would kill all pupils who do not come from all-magical families.',
1683007258510,
1683007258510)

insert into category(`category_id`, `name`) values
    (1, 'Fantasy'), (2, 'Comedy'), (3, 'Crime'), (4, 'Horror'), (5, 'Classic'), (6, 'Self-help'), (7, 'Romance'), (8, 'Kids'), (9, 'Novel'), (10, 'Diary')

insert into users(`name`, `phone`, `address`, `email`, `username`, `password`, `role`, `create_at`) values (N'Trần Quang Minh', '0986153246', '78 Lò Đúc, quận Hai Bà Trưng, Hà Nội', 'minhtq4702@gmail.com', 'admin', 'mKdzv0to!47', 1, 1683007258510), (N'Trần Quang Minh', '0986153247', '78 Lò Đúc, quận Hai Bà Trưng, Hà Nội', 'kin472k2@gmail.com', 'kin472k2', 'mKdzv0to!47', 2, 1683007258510)

insert into liked(`uid`, `book_id`) values
(6, 1),
(7, 1),
(7, 2)

insert into comments(`uid`, `book_id`, `content`, `create_at`) values
(6, 1, 'This book is f*ckin great', 1683007258510),
(7, 1, 'I\'m a Harry Potter fan', 1683007258510),
(7, 2, 'F*ck you Voldermort', 1683007258510)

insert into bookcategories(`book_id`, `category_id`) values (1, 1), (2, 1)